name: flutter_architecture
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design pattern
  flutter_bloc: ^7.0.1
  rxdart: ^0.27.1

  # Common
  retrofit: ^2.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  pedantic: ^1.11.1
  configuration:
    path: ./configuration
  flutter_screenutil: ^5.0.0+2
  get: ^4.3.8
  flutter_svg: ^0.23.0+1
  google_fonts: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  cached_network_image: ^3.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
dev_dependencies:
  build_runner: ^2.0.0
  hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  mockito: ^5.0.10
  bloc_test: ^8.0.0
  json_serializable: ^4.1.3

# There are the packages that can't be update.
#dependency_overrides:
#  pedantic: ^1.9.0
#  mockito: ^4.1.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Gilroy_Medium
      fonts:
        - asset: assets/fonts/Gilroy_Medium.otf

    - family: Gilroy_Regular
      fonts:
        - asset: assets/fonts/Gilroy_Regular.otf

    - family: Gilroy_Bold
      fonts:
        - asset: assets/fonts/Gilroy_Bold.otf

    - family: Gilroy_SemiBold
      fonts:
        - asset: assets/fonts/Gilroy_SemiBold.otf




flutter_intl:
  enabled: true